export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  contentLayer: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    gap: 40,
  },
  card: {
    flex: 1,
    maxWidth: '35%',
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    borderRadius: 20,
    padding: '40px 30px',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.12)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  vsBadge: {
    backgroundColor: '#f59e0b',
    color: '#000000',
    fontSize: 24,
    fontWeight: 'bold',
    padding: '12px 20px',
    borderRadius: 50,
    minWidth: 60,
    textAlign: 'center',
    boxShadow: '0 4px 20px rgba(245, 158, 11, 0.4)',
  },
  cardTitle: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 1.2,
  },
  cardBody: {
    color: '#94a3b8',
    fontSize: 24,
    textAlign: 'center',
    lineHeight: 1.5,
    margin: 0,
  },
  cardIcon: {
    fontSize: 56,
    marginBottom: 20,
    textAlign: 'center',
  },
  header: {
    color: '#ffffff',
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 1.2,
  },
};
