export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  band: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '32%',
    height: '36%',
    background: 'linear-gradient(90deg, rgba(0,0,0,0.75) 0%, rgba(0,0,0,0.55) 50%, rgba(0,0,0,0.75) 100%)',
  },
  captionContainer: {
    position: 'relative',
    zIndex: 1,
    textAlign: 'center',
    maxWidth: '86%',
    padding: '0 40px',
  },
  label: {
    color: '#f59e0b',
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: 5,
    textTransform: 'uppercase',
    marginBottom: 14,
    textAlign: 'center',
  },
  caption: {
    color: '#ffffff',
    fontSize: 64,
    fontWeight: 800,
    textAlign: 'center',
    lineHeight: 1.05,
    letterSpacing: '-0.01em',
    margin: 0,
    textTransform: 'uppercase',
  },
};
