import { spacing, palette } from '../../theme';

export const styles = {
  background: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: `${spacing.xxl}px ${spacing.xxxl}px`,
    boxSizing: 'border-box',
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  ribbon: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    padding: '14px 24px',
    boxSizing: 'border-box',
    overflow: 'hidden',
  },
  ribbonAlt: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 8,
  },
  bigIndex: {
    flexShrink: 0,
    color: palette.accentSolid,
    opacity: 0.35,
    fontSize: 72,
    fontWeight: 800,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    lineHeight: 1,
    marginRight: spacing.lg,
    width: 90,
  },
  ribbonText: {
    minWidth: 0,
  },
  ribbonHeading: {
    color: palette.textOnDark,
    fontSize: 24,
    fontWeight: 600,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    margin: 0,
    marginBottom: 4,
  },
  ribbonBody: {
    color: palette.textMuted,
    fontSize: 18,
    fontWeight: 400,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    lineHeight: 1.4,
    margin: 0,
  },
};
