import { spacing, palette } from '../../theme';

export const styles = {
  background: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: `${spacing.xxl}px ${spacing.xxxl}px`,
    boxSizing: 'border-box',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    gap: spacing.lg,
    width: '100%',
  },
  card: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(148,163,184,0.2)',
    borderRadius: 12,
    padding: '24px 22px',
    boxSizing: 'border-box',
  },
  badge: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    background: palette.accentGradient,
    color: '#0d1117',
    fontSize: 18,
    fontWeight: 700,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  cardHeading: {
    color: palette.textOnDark,
    fontSize: 24,
    fontWeight: 600,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    margin: 0,
    marginBottom: 8,
  },
  cardText: {
    color: palette.textMuted,
    fontSize: 18,
    fontWeight: 400,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    lineHeight: 1.4,
    margin: 0,
  },
};
