export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  title: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 40,
  },
  countdownContainer: {
    display: 'flex',
    flexDirection: 'row',
    gap: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeBlock: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    minWidth: 100,
  },
  timeNumber: {
    color: '#ffffff',
    fontSize: 96,
    fontWeight: 'bold',
    lineHeight: 1,
    marginBottom: 8,
    fontVariantNumeric: 'tabular-nums',
  },
  timeLabel: {
    color: '#94a3b8',
    fontSize: 20,
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  separator: {
    color: 'rgba(96, 165, 250, 0.4)',
    fontSize: 72,
    fontWeight: 'bold',
    lineHeight: 1,
    paddingTop: 10,
  },
  message: {
    color: '#f59e0b',
    fontSize: 28,
    fontWeight: 600,
    textAlign: 'center',
    marginTop: 50,
    letterSpacing: 1,
  },
};
