export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  splitTop: {
    width: '100%',
    height: '50%',
    position: 'relative',
    overflow: 'hidden',
  },
  splitBottom: {
    width: '100%',
    height: '50%',
    position: 'relative',
    overflow: 'hidden',
  },
  splitImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  dividerBar: {
    position: 'absolute',
    top: '50%',
    left: 0,
    right: 0,
    height: 6,
    backgroundColor: 'rgba(96, 165, 250, 0.6)',
    zIndex: 2,
    transform: 'translateY(-50%)',
    boxShadow: '0 0 30px rgba(96, 165, 250, 0.3)',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
    background: 'linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))',
    zIndex: 1,
  },
  label: {
    color: '#f59e0b',
    fontSize: 18,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: 8,
  },
  title: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: 'bold',
    textAlign: 'center',
    textShadow: '0 2px 10px rgba(0,0,0,0.3)',
  },
};
