import { spacing, palette } from '../../theme';

export const styles = {
  background: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: `${spacing.xxl}px ${spacing.xxxl}px`,
    boxSizing: 'border-box',
  },
  timeline: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
    width: '100%',
    maxWidth: '85%',
  },
  timelineLine: {
    position: 'absolute',
    top: 6,
    bottom: 6,
    left: 19,
    width: 2,
    background: palette.accentGradient,
    zIndex: 0,
  },
  row: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  marker: {
    flexShrink: 0,
    width: 40,
    height: 40,
    borderRadius: '50%',
    background: '#0d1117',
    border: `2px solid ${palette.accentSolid}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: palette.textOnDark,
    fontSize: 18,
    fontWeight: 700,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
  },
  rowBody: {
    paddingTop: 4,
  },
  rowHeading: {
    color: palette.textOnDark,
    fontSize: 26,
    fontWeight: 600,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    margin: 0,
    marginBottom: 4,
  },
  rowText: {
    color: palette.textMuted,
    fontSize: 22,
    fontWeight: 400,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    lineHeight: 1.4,
    margin: 0,
  },
};
