export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
  },
  parallaxLayer: {
    position: 'absolute',
    top: '-5%',
    left: '-5%',
    width: '110%',
    height: '110%',
  },
  parallaxImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'linear-gradient(180deg, rgba(0,0,0,0.35) 0%, rgba(0,0,0,0.35) 40%, rgba(0,0,0,0.82) 100%)',
  },
  content: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: '0 90px 100px',
    boxSizing: 'border-box',
  },
  title: {
    color: '#ffffff',
    fontSize: 66,
    fontWeight: 800,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    lineHeight: 1.1,
    margin: 0,
    marginBottom: 18,
    textShadow: '0 4px 24px rgba(0,0,0,0.5)',
  },
  subtitle: {
    color: '#e2e8f0',
    fontSize: 26,
    fontWeight: 400,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    lineHeight: 1.5,
    maxWidth: '80%',
    margin: 0,
  },
};
