import { typography, palette } from '../../theme';

export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'linear-gradient(180deg, rgba(0,0,0,0.15) 0%, rgba(0,0,0,0.25) 45%, rgba(0,0,0,0.88) 100%)',
    zIndex: 1,
  },
  badge: {
    position: 'absolute',
    top: 40,
    left: 40,
    zIndex: 2,
    display: 'inline-block',
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    backdropFilter: 'blur(6px)',
    color: palette.textOnDark,
    fontSize: 16,
    fontWeight: 600,
    padding: '8px 18px',
    borderRadius: 20,
    letterSpacing: 1,
    textTransform: 'uppercase',
    border: `1px solid ${palette.accentSolid}55`,
  },
  textPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    padding: '0 70px 70px',
    boxSizing: 'border-box',
  },
  title: {
    ...typography.title,
    color: palette.textOnDark,
    fontSize: 48,
    fontWeight: 700,
    textAlign: 'left',
    lineHeight: 1.2,
    marginBottom: 14,
    textShadow: '0 2px 12px rgba(0,0,0,0.4)',
  },
  body: {
    ...typography.body,
    color: '#e2e8f0',
    fontSize: 24,
    maxWidth: '85%',
  },
};
