export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    padding: 0,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  imageFull: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  revealOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: '#0f172a',
    zIndex: 1,
  },
  textContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 3,
    padding: '50px 60px',
    background: 'linear-gradient(transparent, rgba(0,0,0,0.85))',
  },
  title: {
    color: '#ffffff',
    fontSize: 42,
    fontWeight: 'bold',
    lineHeight: 1.2,
    marginBottom: 12,
    textShadow: '0 2px 10px rgba(0,0,0,0.3)',
  },
  body: {
    color: '#cbd5e1',
    fontSize: 24,
    lineHeight: 1.4,
    maxWidth: '80%',
  },
  tag: {
    display: 'inline-block',
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    color: '#f59e0b',
    fontSize: 14,
    fontWeight: 600,
    padding: '4px 14px',
    borderRadius: 12,
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
};
