export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 80,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  quoteMark: {
    fontSize: 120,
    color: 'rgba(255, 255, 255, 0.15)',
    fontFamily: 'Georgia, serif',
    lineHeight: 0.8,
    marginBottom: 20,
    textAlign: 'center',
  },
  quoteText: {
    color: '#ffffff',
    fontSize: 44,
    fontWeight: 500,
    textAlign: 'center',
    lineHeight: 1.4,
    maxWidth: '85%',
    fontStyle: 'italic',
    marginBottom: 40,
  },
  authorRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  authorImage: {
    width: 60,
    height: 60,
    borderRadius: '50%',
    objectFit: 'cover',
    border: '2px solid rgba(255, 255, 255, 0.2)',
  },
  authorName: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: 'bold',
  },
  authorTitle: {
    color: '#94a3b8',
    fontSize: 20,
  },
  authorInfo: {
    display: 'flex',
    flexDirection: 'column',
  },
  decorativeLine: {
    width: 80,
    height: 3,
    backgroundColor: '#f59e0b',
    borderRadius: 2,
    marginBottom: 40,
  },
};
