import { typography } from '../../theme';

export const styles = {
  colorBlock: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    clipPath: 'polygon(0 0, 100% 0, 0 100%)',
  },
  darkBlock: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: '#0d1117',
    clipPath: 'polygon(100% 0, 100% 100%, 0 100%)',
    zIndex: 0,
  },
  badge: {
    position: 'absolute',
    top: '38%',
    left: '46%',
    width: 110,
    height: 110,
    borderRadius: '50%',
    overflow: 'hidden',
    zIndex: 1,
    border: '4px solid rgba(255,255,255,0.9)',
    boxShadow: '0 12px 40px rgba(0,0,0,0.4)',
  },
  badgeImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  container: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: '0 90px 110px',
    boxSizing: 'border-box',
  },
  title: {
    ...typography.title,
    textAlign: 'left',
    fontSize: 74,
    fontWeight: 700,
    lineHeight: 1.08,
    marginBottom: 20,
    textShadow: '0 4px 20px rgba(0,0,0,0.35)',
  },
  subtitle: {
    ...typography.subtitle,
    textAlign: 'left',
    fontSize: 27,
    maxWidth: '75%',
  },
};
