export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  contentLayer: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: '90%',
  },
  title: {
    color: '#ffffff',
    fontSize: 48,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 50,
    lineHeight: 1.2,
  },
  timelineLine: {
    position: 'absolute',
    left: '50%',
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: 'rgba(96, 165, 250, 0.3)',
    transform: 'translateX(-50%)',
    borderRadius: 2,
  },
  timelineContainer: {
    position: 'relative',
    width: '100%',
    maxWidth: 900,
    paddingTop: 20,
  },
  cardRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    marginBottom: 30,
    position: 'relative',
  },
  cardRowRight: {
    justifyContent: 'flex-end',
  },
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    borderRadius: 16,
    padding: '24px 32px',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(255, 255, 255, 0.12)',
    maxWidth: '45%',
    width: 'auto',
  },
  cardText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '500',
    lineHeight: 1.3,
    margin: 0,
  },
  cardDate: {
    color: '#60a5fa',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
    letterSpacing: 1,
  },
  dot: {
    position: 'absolute',
    left: '50%',
    width: 16,
    height: 16,
    borderRadius: '50%',
    backgroundColor: '#60a5fa',
    transform: 'translateX(-50%)',
    zIndex: 2,
    boxShadow: '0 0 20px rgba(96, 165, 250, 0.5)',
  },
};
