import { typography, palette } from '../../theme';

export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  wash: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  textPanel: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    maxWidth: '70%',
    padding: '0 40px',
    boxSizing: 'border-box',
  },
  badge: {
    display: 'inline-block',
    backgroundColor: 'rgba(255,255,255,0.18)',
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 600,
    padding: '6px 16px',
    borderRadius: 20,
    marginBottom: 20,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  title: {
    ...typography.title,
    color: palette.textOnDark,
    fontSize: 50,
    fontWeight: 700,
    textAlign: 'center',
    lineHeight: 1.16,
    marginBottom: 18,
    textShadow: '0 4px 20px rgba(0,0,0,0.4)',
  },
  body: {
    ...typography.body,
    color: 'rgba(255,255,255,0.88)',
    fontSize: 22,
    textAlign: 'center',
  },
};
