import { typography, palette } from '../../theme';

export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  dim: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.15)',
  },
  panel: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: '52%',
    boxSizing: 'border-box',
    clipPath: 'polygon(0 0, 84% 0, 62% 100%, 0 100%)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '60px 60px 60px 90px',
  },
  badge: {
    display: 'inline-block',
    backgroundColor: 'rgba(96, 165, 250, 0.18)',
    color: palette.accentSolid,
    fontSize: 16,
    fontWeight: 600,
    padding: '6px 16px',
    borderRadius: 20,
    marginBottom: 20,
    letterSpacing: 1,
    textTransform: 'uppercase',
    alignSelf: 'flex-start',
  },
  title: {
    ...typography.title,
    color: palette.textOnDark,
    fontSize: 46,
    fontWeight: 700,
    textAlign: 'left',
    lineHeight: 1.18,
    marginBottom: 16,
    maxWidth: '80%',
  },
  body: {
    ...typography.body,
    color: palette.textMuted,
    fontSize: 22,
    maxWidth: '75%',
  },
  edgeLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 4,
    background: palette.accentGradient,
    zIndex: 1,
  },
};
