import { createSeededRng, pick } from './seedRandom';

/**
 * Visual Style presets - a lightweight, hand-authored config the rendering
 * engine uses to pick suitable backgrounds/decorations, deliberately kept
 * separate from generateStyle.js's procedural palette/font/shape system.
 * generateStyle.js answers "what colors/fonts/shape language does this
 * video use" (continuous, seed-derived, no fixed list); this answers "what
 * *kind* of visual environment/mood does this video want" (a small curated
 * enum, since backgrounds/decorations are qualitatively different choices,
 * not points on a continuous spectrum). Never generated by the LLM - either
 * an explicit `elements.styleConfig.visualStyle`/`scene.theme.visualStyle`
 * override, or a deterministic per-job pick (see resolveVisualStyle).
 */
export const VISUAL_STYLES = {
  modern: {
    id: 'modern',
    background: { preferred: ['gradient', 'meshGradient', 'glow'], intensity: 0.35 },
    decoration: { preferred: ['floatingShapes', 'dots'], intensity: 0.28 },
  },
  minimal: {
    id: 'minimal',
    background: { preferred: ['solid', 'gradient'], intensity: 0.15 },
    decoration: { preferred: ['dots'], intensity: 0.12 },
  },
  corporate: {
    id: 'corporate',
    background: { preferred: ['gradient', 'solid'], intensity: 0.2 },
    decoration: { preferred: ['geometric', 'dots'], intensity: 0.16 },
  },
  educational: {
    id: 'educational',
    background: { preferred: ['gradient', 'grid'], intensity: 0.25 },
    decoration: { preferred: ['geometric', 'floatingShapes'], intensity: 0.2 },
  },
  technology: {
    id: 'technology',
    background: { preferred: ['grid', 'glow', 'meshGradient'], intensity: 0.35 },
    decoration: { preferred: ['connectingLines', 'dots', 'geometric'], intensity: 0.3 },
  },
  futuristic: {
    id: 'futuristic',
    background: { preferred: ['aurora', 'glow', 'meshGradient'], intensity: 0.4 },
    decoration: { preferred: ['orbit', 'connectingLines'], intensity: 0.32 },
  },
  creative: {
    id: 'creative',
    background: { preferred: ['blobs', 'aurora', 'gradient'], intensity: 0.4 },
    decoration: { preferred: ['floatingShapes', 'waves'], intensity: 0.3 },
  },
  podcast: {
    id: 'podcast',
    background: { preferred: ['gradient', 'glow'], intensity: 0.22 },
    decoration: { preferred: ['dots'], intensity: 0.14 },
  },
};

export const VISUAL_STYLE_IDS = Object.keys(VISUAL_STYLES);

/**
 * Resolves a VisualStyle: an explicit valid `styleId` wins, otherwise a
 * deterministic pick derived from `seedInput` (same seed always resolves to
 * the same style, mirroring generateStyle.js's own seeded pick pattern) so
 * a whole job/video keeps one consistent visual mood without the LLM ever
 * having to name one.
 */
export const resolveVisualStyle = (styleId, seedInput) => {
  if (styleId && VISUAL_STYLES[styleId]) return VISUAL_STYLES[styleId];
  const rng = createSeededRng(`${seedInput ?? 'vireon'}-visual-style`);
  return VISUAL_STYLES[pick(rng, VISUAL_STYLE_IDS)];
};
