export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  bgImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  vignette: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'radial-gradient(ellipse at center, transparent 30%, rgba(0,0,0,0.8) 100%)',
    zIndex: 1,
  },
  content: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 60,
    textAlign: 'center',
    maxWidth: '80%',
  },
  title: {
    color: '#ffffff',
    fontSize: 52,
    fontWeight: 'bold',
    lineHeight: 1.2,
    marginBottom: 20,
    textShadow: '0 4px 30px rgba(0,0,0,0.5)',
  },
  body: {
    color: '#e2e8f0',
    fontSize: 26,
    lineHeight: 1.5,
    textShadow: '0 2px 15px rgba(0,0,0,0.5)',
  },
  accentLine: {
    width: 100,
    height: 3,
    backgroundColor: '#f59e0b',
    borderRadius: 2,
    marginBottom: 30,
  },
};
