export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'row',
    padding: 0,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  leftPanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 80,
    position: 'relative',
    zIndex: 2,
  },
  rightPanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 80,
    position: 'relative',
    zIndex: 1,
    overflow: 'hidden',
  },
  title: {
    color: '#ffffff',
    fontSize: 56,
    fontWeight: 'bold',
    lineHeight: 1.2,
    marginBottom: 24,
    maxWidth: '90%',
  },
  subtitle: {
    color: '#94a3b8',
    fontSize: 28,
    lineHeight: 1.4,
    maxWidth: '85%',
  },
  accentBar: {
    width: 80,
    height: 4,
    backgroundColor: '#60a5fa',
    borderRadius: 2,
    marginBottom: 30,
    alignSelf: 'flex-start',
  },
  statNumber: {
    color: '#60a5fa',
    fontSize: 80,
    fontWeight: 'bold',
    lineHeight: 1,
    marginBottom: 8,
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: 22,
    fontWeight: 500,
  },
  statItem: {
    textAlign: 'center',
    padding: '20px 30px',
  },
  statsRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: 40,
    marginTop: 40,
  },
};
