export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '60px 80px',
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  term: {
    color: '#60a5fa',
    fontSize: 28,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: 12,
  },
  title: {
    color: '#ffffff',
    fontSize: 52,
    fontWeight: 'bold',
    lineHeight: 1.2,
    marginBottom: 20,
  },
  definition: {
    color: '#94a3b8',
    fontSize: 26,
    lineHeight: 1.5,
    marginBottom: 30,
    maxWidth: '90%',
  },
  example: {
    backgroundColor: 'rgba(96, 165, 250, 0.08)',
    borderLeft: '4px solid #60a5fa',
    padding: '20px 28px',
    borderRadius: '0 12px 12px 0',
    marginBottom: 20,
  },
  exampleLabel: {
    color: '#60a5fa',
    fontSize: 16,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  exampleText: {
    color: '#e2e8f0',
    fontSize: 22,
    lineHeight: 1.4,
  },
  divider: {
    width: 60,
    height: 3,
    backgroundColor: '#60a5fa',
    borderRadius: 2,
    marginBottom: 20,
  },
};
