import { typography, palette } from '../../theme';

export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    boxSizing: 'border-box',
    padding: '0 100px',
  },
  glowBlob: {
    position: 'absolute',
    top: '-20%',
    right: '-10%',
    width: '60%',
    height: '80%',
    borderRadius: '50%',
    filter: 'blur(120px)',
    zIndex: 0,
  },
  kicker: {
    position: 'relative',
    zIndex: 1,
    display: 'inline-block',
    color: palette.textOnDark,
    backgroundColor: 'rgba(255,255,255,0.12)',
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: 3,
    textTransform: 'uppercase',
    padding: '8px 20px',
    borderRadius: 999,
    marginBottom: 28,
  },
  title: {
    ...typography.title,
    position: 'relative',
    zIndex: 1,
    textAlign: 'left',
    fontSize: 108,
    fontWeight: 900,
    letterSpacing: '-0.03em',
    lineHeight: 1.02,
    marginBottom: 26,
    textShadow: '0 8px 40px rgba(0,0,0,0.45)',
  },
  subtitle: {
    ...typography.subtitle,
    position: 'relative',
    zIndex: 1,
    textAlign: 'left',
    fontSize: 30,
    maxWidth: '70%',
  },
  thumb: {
    position: 'absolute',
    top: 70,
    right: 90,
    width: 220,
    height: 220,
    borderRadius: 24,
    overflow: 'hidden',
    zIndex: 1,
    boxShadow: '0 20px 60px rgba(0,0,0,0.45)',
    border: '4px solid rgba(255,255,255,0.85)',
  },
  thumbImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
};
