export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  polaroid: {
    backgroundColor: '#ffffff',
    padding: '16px 16px 40px',
    borderRadius: 8,
    boxShadow: '0 20px 60px rgba(0,0,0,0.4)',
    transform: 'rotate(-2deg)',
    maxWidth: '60%',
  },
  polaroid2: {
    backgroundColor: '#ffffff',
    padding: '16px 16px 40px',
    borderRadius: 8,
    boxShadow: '0 20px 60px rgba(0,0,0,0.4)',
    transform: 'rotate(3deg)',
    maxWidth: '55%',
    position: 'absolute',
    top: '55%',
    right: '10%',
    zIndex: 1,
  },
  polaroidImage: {
    width: '100%',
    height: 'auto',
    objectFit: 'cover',
    borderRadius: 4,
    marginBottom: 12,
  },
  polaroidCaption: {
    color: '#333',
    fontSize: 18,
    fontFamily: 'Georgia, serif',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  title: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 30,
    position: 'relative',
    zIndex: 3,
  },
};
