export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  title: {
    color: '#ffffff',
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 40,
  },
  grid: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 24,
    maxWidth: '90%',
  },
  gridItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 16,
    border: '1px solid rgba(255, 255, 255, 0.08)',
    padding: '30px 24px',
    width: 200,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    backdropFilter: 'blur(8px)',
  },
  itemIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  itemTitle: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: 600,
    marginBottom: 8,
  },
  itemDesc: {
    color: '#94a3b8',
    fontSize: 16,
    lineHeight: 1.3,
  },
};
