export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: 0,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  imageLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 0,
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 1,
    background: 'linear-gradient(transparent 50%, rgba(0, 0, 0, 0.8) 100%)',
  },
  captionContainer: {
    position: 'relative',
    zIndex: 2,
    width: '100%',
    padding: '60px 80px 80px',
    boxSizing: 'border-box',
  },
  caption: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 1.4,
    textShadow: '0 2px 10px rgba(0,0,0,0.5)',
  },
  label: {
    color: '#f59e0b',
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 3,
    textTransform: 'uppercase',
    marginBottom: 12,
    textAlign: 'center',
  },
};
