export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  title: {
    color: '#ffffff',
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 50,
  },
  cardRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: 30,
    justifyContent: 'center',
    flexWrap: 'wrap',
    maxWidth: '90%',
  },
  profileCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 20,
    padding: '40px 30px',
    width: 280,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    backdropFilter: 'blur(8px)',
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: '50%',
    objectFit: 'cover',
    marginBottom: 20,
    border: '3px solid rgba(96, 165, 250, 0.3)',
  },
  name: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 6,
    textAlign: 'center',
  },
  role: {
    color: '#60a5fa',
    fontSize: 20,
    fontWeight: 500,
    marginBottom: 12,
    textAlign: 'center',
  },
  bio: {
    color: '#94a3b8',
    fontSize: 18,
    textAlign: 'center',
    lineHeight: 1.4,
  },
};
