export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  contentLayer: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '80%',
  },
  questionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    padding: '50px 60px',
    marginBottom: 30,
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    width: '100%',
    maxWidth: '90%',
  },
  answerCard: {
    backgroundColor: 'rgba(96, 165, 250, 0.15)',
    borderRadius: 20,
    padding: '50px 60px',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(96, 165, 250, 0.3)',
    width: '100%',
    maxWidth: '90%',
  },
  questionText: {
    color: '#ffffff',
    fontSize: 48,
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 1.3,
  },
  answerText: {
    color: '#60a5fa',
    fontSize: 40,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 1.3,
  },
  arrow: {
    color: '#f59e0b',
    fontSize: 36,
    marginBottom: 20,
    textAlign: 'center',
  },
  icon: {
    fontSize: 48,
    marginBottom: 16,
    textAlign: 'center',
  },
};
