export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  backgroundLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 0,
  },
  contentLayer: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '80%',
  },
  imageWrapper: {
    width: 400,
    height: 300,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 40,
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  title: {
    color: '#ffffff',
    fontSize: 64,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 1.2,
    textShadow: '0 2px 10px rgba(0,0,0,0.3)',
  },
  subtitle: {
    color: '#94a3b8',
    fontSize: 32,
    textAlign: 'center',
    lineHeight: 1.4,
    maxWidth: '80%',
  },
};
