export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'center',
    boxSizing: 'border-box',
  },
  backdropLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  backdropImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    filter: 'blur(18px) saturate(1.1)',
    transform: 'scale(1.15)',
  },
  backdropTint: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(13, 17, 23, 0.55)',
  },
  frameWrap: {
    position: 'absolute',
    top: '8%',
    left: '10%',
    right: '10%',
    bottom: '24%',
    borderRadius: 20,
    overflow: 'hidden',
    boxShadow: '0 30px 80px rgba(0,0,0,0.55)',
    border: '6px solid rgba(255,255,255,0.9)',
  },
  echoFrame: {
    position: 'absolute',
    top: '11%',
    left: '14%',
    right: '6%',
    bottom: '20%',
    borderRadius: 20,
    overflow: 'hidden',
    border: '6px solid rgba(255,255,255,0.35)',
    zIndex: 0,
  },
  frameImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'linear-gradient(transparent 60%, rgba(0, 0, 0, 0.9) 100%)',
    zIndex: 2,
  },
  captionContainer: {
    position: 'relative',
    zIndex: 3,
    width: '100%',
    padding: '60px 80px 60px',
    boxSizing: 'border-box',
  },
  caption: {
    color: '#ffffff',
    fontSize: 34,
    fontWeight: 600,
    textAlign: 'center',
    lineHeight: 1.4,
    textShadow: '0 2px 10px rgba(0,0,0,0.5)',
  },
  label: {
    color: '#f59e0b',
    fontSize: 20,
    fontWeight: 600,
    letterSpacing: 3,
    textTransform: 'uppercase',
    marginBottom: 12,
    textAlign: 'center',
  },
};
