import { spacing, palette } from '../../theme';

export const styles = {
  background: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: `${spacing.xxl}px ${spacing.xxxl}px`,
    boxSizing: 'border-box',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    gap: spacing.xl,
    width: '100%',
  },
  tileGroup: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  tile: {
    width: 56,
    height: 56,
    borderRadius: 12,
    background: palette.accentGradient,
    color: '#0d1117',
    fontSize: 26,
    fontWeight: 700,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  tileHeading: {
    color: palette.textOnDark,
    fontSize: 21,
    fontWeight: 600,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    margin: 0,
    marginBottom: 6,
  },
  tileText: {
    color: palette.textMuted,
    fontSize: 16,
    fontWeight: 400,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    lineHeight: 1.35,
    margin: 0,
  },
};
