import { spacing, palette } from '../../theme';

export const styles = {
  background: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: `${spacing.xxl}px ${spacing.xxxl}px`,
    boxSizing: 'border-box',
  },
  pathRow: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  connector: {
    position: 'absolute',
    top: 30,
    left: 30,
    right: 30,
    height: 3,
    background: palette.accentGradient,
    zIndex: 0,
  },
  node: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '22%',
  },
  nodeCircle: {
    width: 60,
    height: 60,
    borderRadius: '50%',
    background: palette.accentGradient,
    color: '#0d1117',
    fontSize: 22,
    fontWeight: 700,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 0 0 6px rgba(13,17,23,1)',
  },
  nodeText: {
    marginTop: spacing.md,
    textAlign: 'center',
  },
  nodeHeading: {
    color: palette.textOnDark,
    fontSize: 21,
    fontWeight: 600,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    margin: 0,
    marginBottom: 6,
  },
  nodeBody: {
    color: palette.textMuted,
    fontSize: 16,
    fontWeight: 400,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    lineHeight: 1.35,
    margin: 0,
  },
};
