export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  parallaxLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '120%',
    zIndex: 0,
  },
  parallaxImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'linear-gradient(135deg, rgba(0,0,0,0.7) 0%, rgba(0,0,0,0.3) 100%)',
    zIndex: 1,
  },
  content: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 60,
    textAlign: 'center',
  },
  title: {
    color: '#ffffff',
    fontSize: 56,
    fontWeight: 'bold',
    lineHeight: 1.2,
    marginBottom: 20,
    textShadow: '0 4px 20px rgba(0,0,0,0.3)',
  },
  subtitle: {
    color: '#e2e8f0',
    fontSize: 28,
    lineHeight: 1.4,
    maxWidth: '70%',
    textShadow: '0 2px 10px rgba(0,0,0,0.3)',
  },
  cta: {
    marginTop: 40,
    padding: '16px 48px',
    backgroundColor: '#60a5fa',
    color: '#ffffff',
    fontSize: 24,
    fontWeight: 600,
    borderRadius: 50,
    border: 'none',
    boxShadow: '0 8px 30px rgba(96, 165, 250, 0.3)',
  },
};
