import { spacing, palette } from '../../theme';

export const styles = {
  background: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: `${spacing.xxl}px ${spacing.xxxl}px`,
    boxSizing: 'border-box',
  },
  dek: {
    color: palette.textOnDark,
    fontSize: 28,
    fontWeight: 400,
    fontStyle: 'italic',
    fontFamily: "Georgia, 'Times New Roman', serif",
    lineHeight: 1.5,
    borderLeft: `3px solid ${palette.accentSolid}`,
    paddingLeft: spacing.lg,
    margin: 0,
    marginBottom: spacing.lg,
    maxWidth: '85%',
  },
  dekHeading: {
    fontWeight: 700,
    fontStyle: 'normal',
  },
  rule: {
    width: '100%',
    maxWidth: '85%',
    height: 1,
    background: 'rgba(148,163,184,0.3)',
    marginBottom: spacing.lg,
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    width: '100%',
    maxWidth: '85%',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: spacing.md,
  },
  index: {
    flexShrink: 0,
    color: palette.accentSolid,
    fontSize: 16,
    fontWeight: 700,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    letterSpacing: 1,
  },
  rowHeading: {
    color: palette.textOnDark,
    fontSize: 19,
    fontWeight: 600,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
  },
  rowText: {
    color: palette.textMuted,
    fontSize: 18,
    fontWeight: 400,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    lineHeight: 1.4,
  },
};
