import { spacing, palette } from '../../theme';

export const styles = {
  background: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: `${spacing.xxl}px ${spacing.xxxl}px`,
    boxSizing: 'border-box',
  },
  mark: {
    color: palette.accentSolid,
    fontSize: 100,
    fontWeight: 700,
    fontFamily: "Georgia, 'Times New Roman', serif",
    lineHeight: 1,
    marginBottom: -20,
  },
  quote: {
    color: palette.textOnDark,
    fontSize: 40,
    fontWeight: 400,
    fontStyle: 'italic',
    fontFamily: "Georgia, 'Times New Roman', serif",
    lineHeight: 1.35,
    margin: 0,
    marginBottom: spacing.lg,
    maxWidth: '85%',
  },
  attribution: {
    color: palette.accentSolid,
    fontSize: 20,
    fontWeight: 600,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    letterSpacing: 1,
    margin: 0,
    marginBottom: spacing.xl,
  },
  footnoteRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: `${spacing.sm}px ${spacing.xl}px`,
    borderTop: '1px solid rgba(148,163,184,0.25)',
    paddingTop: spacing.md,
    width: '100%',
    maxWidth: '85%',
  },
  footnote: {
    fontSize: 15,
  },
  footnoteHeading: {
    color: palette.textOnDark,
    fontWeight: 600,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
  },
  footnoteText: {
    color: palette.textMuted,
    fontWeight: 400,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
  },
};
