export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  vignette: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'radial-gradient(ellipse at center, transparent 40%, rgba(0,0,0,0.92) 100%)',
  },
  darken: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.25)',
  },
  content: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: '0 90px 90px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
  },
  accentLine: {
    width: 60,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#fbbf24',
    marginBottom: 18,
  },
  label: {
    color: '#fbbf24',
    fontSize: 16,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 3,
    marginBottom: 10,
  },
  caption: {
    color: '#f5f5f0',
    fontSize: 32,
    fontWeight: 600,
    lineHeight: 1.4,
    maxWidth: '78%',
    margin: 0,
    textShadow: '0 2px 14px rgba(0,0,0,0.6)',
  },
};
