import { typography } from '../../theme';

export const styles = {
  stripes: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '140%',
    height: '100%',
    background: 'repeating-linear-gradient(115deg, #1a1a2e 0px, #1a1a2e 90px, #16213e 90px, #16213e 180px)',
  },
  dim: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'linear-gradient(180deg, rgba(0,0,0,0.15) 0%, rgba(0,0,0,0.6) 100%)',
  },
  thumb: {
    position: 'absolute',
    top: 60,
    right: 70,
    width: 220,
    height: 220,
    borderRadius: 12,
    overflow: 'hidden',
    transform: 'rotate(4deg)',
    boxShadow: '0 20px 50px rgba(0,0,0,0.5)',
    border: '3px solid rgba(255,255,255,0.85)',
  },
  thumbImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  container: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '0 90px',
    boxSizing: 'border-box',
  },
  badge: {
    display: 'inline-block',
    alignSelf: 'flex-start',
    color: '#0d1117',
    fontSize: 18,
    fontWeight: 800,
    letterSpacing: 1,
    textTransform: 'uppercase',
    padding: '8px 22px',
    borderRadius: 4,
    transform: 'skewX(-8deg)',
    marginBottom: 26,
  },
  title: {
    ...typography.title,
    textAlign: 'left',
    fontSize: 96,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '-0.01em',
    lineHeight: 0.98,
    marginBottom: 24,
    textShadow: '0 6px 30px rgba(0,0,0,0.5)',
  },
  subtitle: {
    ...typography.subtitle,
    textAlign: 'left',
    fontSize: 28,
    maxWidth: '65%',
  },
};
