export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    boxSizing: 'border-box',
  },
  paperTexture: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'radial-gradient(ellipse at center, #efe6d2 0%, #ddd0ae 100%)',
  },
  frame: {
    position: 'relative',
    width: '68%',
    height: '66%',
    boxSizing: 'border-box',
    padding: 22,
    backgroundColor: '#fbf6ea',
    boxShadow: '0 20px 60px rgba(60,44,20,0.35)',
    border: '1px solid rgba(120,96,60,0.35)',
  },
  frameInner: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    border: '1px solid rgba(120,96,60,0.25)',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    filter: 'sepia(0.12) contrast(1.02)',
  },
  noteWrap: {
    position: 'relative',
    marginTop: 28,
    textAlign: 'center',
    maxWidth: '70%',
  },
  label: {
    color: '#7c6a44',
    fontSize: 16,
    fontWeight: 700,
    letterSpacing: 3,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  caption: {
    color: '#3a2e1c',
    fontSize: 28,
    fontWeight: 400,
    fontStyle: 'italic',
    fontFamily: "Georgia, 'Times New Roman', serif",
    lineHeight: 1.5,
    margin: 0,
  },
};
