export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  title: {
    color: '#ffffff',
    fontSize: 44,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 60,
  },
  statsGrid: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 30,
    maxWidth: '90%',
  },
  statCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 20,
    padding: '40px 50px',
    minWidth: 220,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    backdropFilter: 'blur(8px)',
  },
  statValue: {
    color: '#60a5fa',
    fontSize: 72,
    fontWeight: 'bold',
    lineHeight: 1,
    marginBottom: 8,
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: 22,
    fontWeight: 500,
    textAlign: 'center',
  },
  statIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
};
