export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  wash: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  captionContainer: {
    position: 'relative',
    zIndex: 1,
    textAlign: 'center',
    maxWidth: '72%',
    padding: '0 40px',
  },
  label: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: 4,
    textTransform: 'uppercase',
    marginBottom: 18,
    textAlign: 'center',
    opacity: 0.85,
  },
  caption: {
    color: '#ffffff',
    fontSize: 44,
    fontWeight: 700,
    textAlign: 'center',
    lineHeight: 1.25,
    margin: 0,
    textShadow: '0 6px 30px rgba(0,0,0,0.35)',
  },
};
