import { typography, palette } from '../../theme';

export const styles = {
  outer: {
    width: '100%',
    height: '100%',
    position: 'relative',
    boxSizing: 'border-box',
    padding: 56,
  },
  frame: {
    position: 'relative',
    width: '100%',
    height: '100%',
    border: '1px solid rgba(148,163,184,0.35)',
    borderRadius: 4,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '0 110px',
    overflow: 'hidden',
  },
  ruleTop: {
    position: 'absolute',
    top: 64,
    left: 110,
    width: 90,
    height: 3,
    background: '#60a5fa',
  },
  kicker: {
    color: '#94a3b8',
    fontSize: 20,
    fontWeight: 600,
    letterSpacing: 6,
    textTransform: 'uppercase',
    margin: 0,
    marginBottom: 22,
  },
  title: {
    ...typography.title,
    textAlign: 'left',
    fontSize: 78,
    fontWeight: 500,
    letterSpacing: '-0.01em',
    lineHeight: 1.12,
    marginBottom: 24,
  },
  divider: {
    width: '100%',
    maxWidth: 560,
    height: 1,
    background: 'rgba(148,163,184,0.3)',
    marginBottom: 24,
  },
  subtitle: {
    ...typography.subtitle,
    textAlign: 'left',
    fontSize: 26,
    maxWidth: '60%',
  },
  thumb: {
    position: 'absolute',
    top: 64,
    right: 64,
    width: 180,
    height: 240,
    overflow: 'hidden',
    border: '1px solid rgba(148,163,184,0.35)',
  },
  thumbImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  ruleBottom: {
    position: 'absolute',
    bottom: 56,
    left: 110,
    right: 110,
    height: 1,
    background: 'rgba(148,163,184,0.25)',
  },
};
