export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '60px 80px',
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 50,
    gap: 16,
  },
  emoji: {
    fontSize: 56,
  },
  title: {
    color: '#ffffff',
    fontSize: 44,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  stepsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    width: '100%',
    maxWidth: 900,
    margin: '0 auto',
  },
  stepRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 24,
    padding: '20px 0',
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
  },
  stepNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#60a5fa',
    backgroundColor: 'rgba(96, 165, 250, 0.1)',
    width: 48,
    height: 48,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: 600,
    marginBottom: 4,
  },
  stepDesc: {
    color: '#94a3b8',
    fontSize: 20,
    lineHeight: 1.3,
  },
};
