const crypto = require('crypto');
const config = require('../../config');
const LoggerService = require('../common/LoggerService');

/**
 * A per-key mutex over Redis, for ONE purpose: letting a second process notice that an
 * identical artifact is already being generated by another and wait for it, instead of
 * generating it again (services/cache/GenerationCoordinator.js).
 *
 * Deliberately weak where it can afford to be. It is an optimisation, never a gate: if
 * Redis is down or slow the caller simply carries on and generates (a duplicate costs
 * time, a blocked generation costs the job), so every method fails fast and reports
 * "unavailable" instead of retrying.
 *
 * Fixed-TTL locks are renewed by the holder while it works, so a long GPU generation
 * does not lose its lock to its own clock, and a holder that dies loses it within one TTL.
 */

const RELEASE = `
if redis.call("GET", KEYS[1]) == ARGV[1] then
  return redis.call("DEL", KEYS[1])
end
return 0
`;
const EXTEND = `
if redis.call("GET", KEYS[1]) == ARGV[1] then
  return redis.call("PEXPIRE", KEYS[1], ARGV[2])
end
return 0
`;

class RedisKeyLock {
  constructor({ host = config.redis.host, port = config.redis.port } = {}) {
    this._host = host;
    this._port = port;
    this._client = null;
  }

  _redis() {
    if (!this._client) {
      const Redis = require('ioredis');
      this._client = new Redis({
        host: this._host,
        port: this._port,
        lazyConnect: true,
        // Fail fast: this is an optimisation and must never hold up a generation.
        maxRetriesPerRequest: 1,
        enableOfflineQueue: false,
        connectTimeout: 1500,
        commandTimeout: 1500,
        retryStrategy: () => null,
      });
      this._client.on('error', (err) => LoggerService.debug('[Cache lock] redis error', { error: err.message }));
    }
    return this._client;
  }

  static _key(name) {
    return `cache-gen:${name}`;
  }

  /** @returns {Promise<{ acquired: true, token: string } | { acquired: false }>} throws if Redis is unavailable */
  async acquire(name, ttlMs) {
    const client = this._redis();
    if (client.status === 'wait' || client.status === 'end') await client.connect();
    const token = crypto.randomUUID();
    const ok = await client.set(RedisKeyLock._key(name), token, 'PX', ttlMs, 'NX');
    return ok === 'OK' ? { acquired: true, token } : { acquired: false };
  }

  async isHeld(name) {
    return (await this._redis().exists(RedisKeyLock._key(name))) === 1;
  }

  async extend(name, token, ttlMs) {
    return (await this._redis().eval(EXTEND, 1, RedisKeyLock._key(name), token, String(ttlMs))) === 1;
  }

  async release(name, token) {
    return (await this._redis().eval(RELEASE, 1, RedisKeyLock._key(name), token)) === 1;
  }

  async close() {
    if (this._client) {
      await this._client.quit().catch(() => {});
      this._client = null;
    }
  }
}

module.exports = { RedisKeyLock };
