import { typography, palette } from '../../theme';

export const styles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  quoteGlyph: {
    position: 'absolute',
    top: -80,
    left: 40,
    fontSize: 340,
    fontWeight: 700,
    fontFamily: "Georgia, 'Times New Roman', serif",
    color: 'rgba(255,255,255,0.05)',
    lineHeight: 1,
    zIndex: 0,
  },
  corner: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: '52%',
    height: '62%',
    overflow: 'hidden',
    clipPath: 'polygon(18% 0, 100% 0, 100% 100%, 0 100%)',
    zIndex: 1,
    boxShadow: '-30px 30px 60px rgba(0,0,0,0.35)',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  textPanel: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    width: '58%',
    height: '100%',
    padding: '0 0 70px 80px',
    boxSizing: 'border-box',
  },
  badge: {
    display: 'inline-block',
    backgroundColor: 'rgba(96, 165, 250, 0.18)',
    color: palette.accentSolid,
    fontSize: 15,
    fontWeight: 600,
    padding: '5px 14px',
    borderRadius: 20,
    marginBottom: 18,
    letterSpacing: 1,
    textTransform: 'uppercase',
    alignSelf: 'flex-start',
  },
  title: {
    ...typography.title,
    color: palette.textOnDark,
    fontSize: 44,
    fontWeight: 700,
    textAlign: 'left',
    lineHeight: 1.18,
    marginBottom: 16,
  },
  body: {
    ...typography.body,
    color: palette.textMuted,
    fontSize: 20,
    maxWidth: '90%',
  },
};
