export const styles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '80px 100px',
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
  },
  title: {
    color: '#ffffff',
    fontSize: 44,
    fontWeight: 'bold',
    marginBottom: 50,
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
    width: '100%',
  },
  listItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    padding: '20px 30px',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 14,
    border: '1px solid rgba(255, 255, 255, 0.06)',
  },
  bulletIcon: {
    fontSize: 32,
    minWidth: 44,
    height: 44,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(96, 165, 250, 0.15)',
  },
  bulletText: {
    color: '#e2e8f0',
    fontSize: 28,
    fontWeight: 500,
    lineHeight: 1.3,
    flex: 1,
  },
};
